### ISSUE TITLE
Review whether User and City registry contracts need to implement extension-trait

### ISSUE THREAD

**Issue by radicleart** [citycoins/protocol#30]
Review whether these two contracts need to implement the extension trait. They're controlled by the dao but do not themselves need to implement extension-trait. This may change as the functionality unfolds.

**Comment by whoabuddy** [comment]
We should probably leave things as-is now as to eliminate introducing any confusion.

- proposals = one-time actions
- extensions = standing functionality

Also since both contracts use `is-dao-or-extension` and `.base-dao is-extension` to determine if its active, it might be more confusing to say this *isn't an extension*.
